### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by levyadams** [jongallant/WorldGeneratorFinal#5]
I loved the tutorial, but it seems like the website is down now? What a travesty!

**Comment by MelleDijkstra** [comment]
You mean this website: http://www.jgallant.com/
For me it's working fine!
Check: https://downforeveryoneorjustme.com/www.jgallant.com

**Comment by levyadams** [comment]
Oh wow, I am so glad I am wrong!

Now that I have you here, before you close this, would you elaborate a bit on how you've come to understand and create this tutorial? I've been coding for years, and some of the things you do here are so outside of my natural ability. How did you start learning these practices and algos?

:D

**Comment by MelleDijkstra** [comment]
@levyadams Are you referring to me? Sorry to disappoint you, I'm not the creator of the tutorials, just a curious outsider. However, the best tip I can give you is to practice A LOT! Just start with reading and coding such tutorials and try to come up with something which is not explained in the tutorial. Try to improve it with your own creative ideas. Not only is this fun it checks if you really understand what is going on in the code. Hope that helps ;p Who knows the actual creator has some more insights! Good day to you both. 😉

**Comment by jongallant** [comment]
@levyadams I have been coding since the 90s.  This particular series was extracted out of a game I had written over the course of approximately 3 years.  It took a lot of time, research, and effort in order for me to get a good understanding of how to manipulate data in such a way.

The idea was for me to share some of my knowledge back with the community.  There is actually a continuation series that I have been meaning to write.  I will eventually get back to it at some point.
